// <auto-generated />
namespace OfficeAutomation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_address));
        
        string IMigrationMetadata.Id
        {
            get { return "201807120557418_add_address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
